---
title: "Mapping a State with Small Mainland"
description: |
  Plotting number of homicides on a state map with a small mainland map using `ggplot`
date: 11-15-2020
categories:
  - map
output:
  distill::distill_article:
    self_contained: false
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE
)
library(dplyr)
library(ggplot2)
library(tigris)
library(rcartocolor)
library(cowplot)
```

### Data preperation
Load UCR dataset, geographic information data and merge them.

```{r message=FALSE, warning=FALSE, results='hide'}
# load UCR data and rename it
load("../../datasets/37059-0001-Data.rda")
ucr <- da37059.0001

# US states and countries are available in `tigris` package
usstates <- states(cb = TRUE) %>% filter(!(STATEFP %in% c("02","15","60","66","69","72","78")))
uscounties <- counties(cb = TRUE) %>% filter(!(STATEFP %in% c("60","66","69","72","78")))

# we need to convert numeric state FIPS code variable (`FIPS_CTY`) into a string variable 
# and add a leading zero to one digit codes
for(i in 1:length(ucr$FIPS_ST)){
  if(ucr$FIPS_ST[i] < 10){
    ucr$CHR_FIPS_ST[i] <- paste(0, as.character(ucr$FIPS_ST[i]), sep = "")
  }else{
    ucr$CHR_FIPS_ST[i] <- as.character(ucr$FIPS_ST[i])
  }
}

# a similar recoding for county FIPS code
for(i in 1:length(ucr$FIPS_CTY)){
  if(ucr$FIPS_CTY[i] < 10){
    ucr$CHR_FIPS_CTY[i] <- paste("00", as.character(ucr$FIPS_CTY[i]), sep = "")
  }else if(ucr$FIPS_CTY[i] < 100 & ucr$FIPS_CTY[i] > 9 ){
    ucr$CHR_FIPS_CTY[i] <- paste("0", as.character(ucr$FIPS_CTY[i]), sep = "")
  }else{
    ucr$CHR_FIPS_CTY[i] <- as.character(ucr$FIPS_CTY[i])
  }
}

# create a key to merge two datasets
ucr$FIPS_ST_CTY <- paste(ucr$CHR_FIPS_ST,ucr$CHR_FIPS_CTY,sep="")
uscounties$FIPS_ST_CTY <- paste(uscounties$STATEFP, uscounties$COUNTYFP, sep="")

#merge two datasets
geo_ucr_counties <- left_join(uscounties, ucr, key = "FIPS_ST_CTY")

#get state data (CA in this case)
geo_ucr_state <- geo_ucr_counties %>% 
  filter(CHR_FIPS_ST == "06")
```

### Mapping
Plot homicide on state map using `ggplot`:

```{r}
usMain <- ggplot() + 
  geom_sf(data = usstates, fill = "white") +
  geom_sf(data = geo_ucr_state, fill = NA, color = "red", size = 1.2) +
  theme_void()

usState = ggplot() + 
  geom_sf(data = geo_ucr_state, aes(fill = MURDER)) +
  scale_fill_carto_c(palette = "Mint") +
  labs(fill = "Homicide") +
  theme_void() +
  theme(legend.position = c(0.1, 0.05),
        legend.direction = "horizontal",
        legend.key.width = unit(10, "mm"))

insetMap = ggdraw() +
  draw_plot(usState) +
  draw_plot(usMain, x = 0.65, y = 0.65, width = 0.3, height = 0.3)
  #need to change locaton of mainland according to the shape of the state

insetMap

```


